### ISSUE TITLE
Add a cd maybe

### ISSUE THREAD

**Issue by danielmkarlsson** [C0dereview/c0dereview.github.io#3]
Maybe we should add "cd into your forked c0dereview.gihub.io directory" or similar at the top of Step 4 of writing posts for c0dereview? It could go at the bottom of step 3 also. 
Not sure how to phrase that instruction.

**Comment by davidgranstrom** [comment]
Sounds like a good suggestion. 

I'll also add a link to the README of this repo if someone would like to read instructions on how to preview their changes locally.
